#define INPUT_LIGHT A0
#define INPUT_BUTTON_LEFT 16
#define INPUT_BUTTON_RIGHT 5
#define INPUT_BUTTON_UP 13
#define INPUT_BUTTON_DOWN 15
#define INPUT_BUTTON_ENTER 4

#define AIR_DATA_COLLECTION_TIME 2000
#define LIGHT_DATA_COLLECTION_TIME 1000
#define DISPLAY_UPDATE_TIME 1000
#define DISPLAY_ON_TIME 20000
#define MQTT_DATA_UPDATE_TIME 300000